name: Deploy Snowflake Apps

on:
  push:
    branches:
      - dev
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: suryaph971/snowparkdev
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Snowflake
        working-directory: surya_snowpark_project
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER_DEV }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD_DEV }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE_DEV }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_DEV }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE_DEV }}
        run: python deploy_snowpark_app.py $GITHUB_WORKSPACE/surya_snowpark_project